[project]
name = "ComfyUI-TKVideoZoom"
description = "Various Zoom/Slide effects for Video"
version = "1.06"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/trashkollector/TKVideoZoom"

[tool.comfy]
PublisherId = "trashkollector"
DisplayName = "ComfyUI-TKVideoZoom"
Icon = ""
